### ISSUE TITLE
Starting chat error using Crisp 1.0.6 

### ISSUE THREAD

**Issue by wxsdmy** [crisp-im/crisp-sdk-ios#38] opened 2020-12-31 03:37 UTC
Xcode12.3, iOS14.3, iPhone6s、iPhone11
Initialized Crisp Crisp SDK Version 1.0.6 (Build 93).
[error] We could not connect to the chat. Try again now, or later.

https://user-images.githubusercontent.com/13514560/103393144-3bf63e00-4b5c-11eb-9681-326c3ea700e3.MP4

**Comment by eliottvincent** [comment] 2020-12-31 13:14
Hey @wxsdmy, could you please check the Xcode debug console? There should be a debug message there.

**Comment by nesium** [comment] 2020-12-31 14:07
Judging from the duration (15 seconds) this looks like a timeout. But from my testing it should in addition to the quoted error message print either: `[error] The request timed out.` or `[error] cancelled`.

**Comment by wxsdmy** [comment] 2021-01-04 02:10
@eliottvincent , 1.0.8 had same issue. No other debug message printed in the Xcode debug console, except: Initialized Crisp Crisp SDK Version 1.0.8 (Build 95).
[error] We could not connect to the chat. Try again now, or later.
Is there a debug log switch in the SDK? And how can I open the debug bug?

**Comment by trevinwisaksana** [comment] 2021-01-07 05:32
I'm using version 1.0.8 and I'm also facing the same issue but the error that came out is: `[error] Socket disabled`

**Comment by nesium** [comment] 2021-01-07 10:15
Thanks for reporting!

@wxsdmy @trevinwisaksana Just to give me a better understanding on how to reproduce this:
- Is this an intermittent issue or is this reproducible 100% of the time?
- If it is intermittent: Does it only happen, say, when you switch away from the app and then back? 
- Did the chat disconnect for any reason? (it shows a banner at the top if this happens)
- Does it only happen on the device but works in the simulator?

Thanks for your help!

**Comment by wxsdmy** [comment] 2021-01-08 11:23
@trevinwisaksana This reproducible 100% of the time and is not intermittent. It happens on the device but works on most of simulators, and it works on Android.

**Comment by nesium** [comment] 2021-01-08 13:22
Thanks, @wxsdmy. Is your iOS device (in contrast to the simulator or Android device) by any chance on a different Wifi or on a mobile network? Does it have a VPN activated? Or put differently: Does your iOS device use the same external IP as your simulator and Android device?

**Comment by wxsdmy** [comment] 2021-01-08 15:38
@nesium. Yes, iOS device, simulator and android device are on the same WiFi. We also changed to different WiFi, routers or mobile networks, but not work. We do not have a VPN activated. Maybe, some network limits in China on iOS.

**Comment by archerwindy** [comment] 2021-01-10 17:25
Same error here with message: `[error] We could not connect to the chat. Try again now, or later.`
I'm using Xcode 12.3 and version 1.0.8.

**Comment by Uniphix** [comment] 2021-01-28 23:11
> Same error here with message: `[error] We could not connect to the chat. Try again now, or later.`
> I'm using Xcode 12.3 and version 1.0.8.

I am getting the same error.

**Comment by nesium** [comment] 2021-02-01 14:40
@trevinwisaksana This issue should finally be fixed in the 1.0.9 release. Let us know if you still encounter the issue.

**Comment by wxsdmy** [comment] 2021-02-02 03:33
@nesium Same error here with message: [error] We could not connect to the chat. Try again now, or later. in 1.0.9.
However, we have a discovery in the iOS simulator. If we use the simulator with system language “English”,  it works. But if we change the system language to Chinese “简体中文”, it doesn't work. And we change back to “English” or other languages , it doesn't work too.

**Comment by nesium** [comment] 2021-02-02 11:28
@wxsdmy Thanks for testing and your sharp observation! That helped triage an undiscovered problem where the iOS SDK was sending language codes for certain locales in a format the server didn't understand. If you could please try again with the 1.0.10 release and let us know if that fixes your problem. Thanks again!

**Comment by wxsdmy** [comment] 2021-02-03 02:28
@nesium Fixed in the 1.0.10 release, thanks!

**Closed** 2021-02-03 08:20 UTC
