### ISSUE TITLE
CrispChat showing Error Starting chat page and error while showing ChatView.

### ISSUE THREAD

**Issue by AnishaLamichhane11** [crisp-im/crisp-sdk-ios#93] opened 2024-01-23 07:08 UTC
The issue I am facing is, the chat view is shown and then it freezes some times when I try to send message.
And after I try it several times it shows error Starting chat.
This issue is not in web or android, it only occurs in iOS. 
I am using version 2.4.4

**Comment by nesium** [comment] 2024-01-24 14:15
Hi @AnishaLamichhane11. Thanks for your report.

When you say "it freezes" do you mean that the whole app where the SDK is embedded in hangs? If so could you pause in the debugger and send a screenshot of what the stack looks like?

If it's just the ChatView that doesn't react as it is supposed to, what does it show during the freeze, before it says "error Starting Chat"?

**Comment by AnishaLamichhane11** [comment] 2024-01-25 02:36
There are actually two different issues.
1. The app freezes (only crispchat view), it only happens sometimes. I cannot recreate this issue at the moment, will send you screenshot as soon as it occurs again.
2. The crisp chat loads and cannot load the crispchat view and retry again view is shown. I have attached the video from the app. Do  check it out.

https://github.com/crisp-im/crisp-sdk-ios/assets/157456092/6d519c2c-d76d-4ff4-a486-562769eeea13

FYI : We are using SwiftUI

**Comment by nesium** [comment] 2024-01-29 15:48
Thanks, @AnishaLamichhane11.

For 2. you should see a message in the Xcode console. Something along the lines of…

> [Crisp] Error: Expected to decode ...

Could you please share what that message says?

**Comment by AnishaLamichhane11** [comment] 2024-01-30 02:14
For 2. This is the message shown in Xcode console.
 [Crisp] Error: TimeoutError()

**Comment by baptistejamin** [comment] 2024-01-30 07:42
There TImeout error is likely due to a network issue, a VPN or something like this. Try using the web version, using Safari on your simulator and you'll see

**Comment by AnishaLamichhane11** [comment] 2024-01-31 03:17
I don't think this is a network issue. 
1. In mobile app (iOS) the chatview freezes as shown in the screenshot below.
![IMG_7009](https://github.com/crisp-im/crisp-sdk-ios/assets/157456092/217995a0-ecd1-4ecc-bcfe-489b245ac5e2)
First the crispchat is working fine and after multiple chats it freezes . Only this chat screen is freezed and the overall app is not affected. Also no debug message is printed in Xcode console. 

2. In safari the chat is working fine. (The below recording is done in the safari app of same device.)
https://github.com/crisp-im/crisp-sdk-ios/assets/157456092/ca72c3a2-c970-4b31-806a-cdeeb8145f36

**Comment by nesium** [comment] 2024-01-31 11:33
Thanks for confirming that this is not a network issue @AnishaLamichhane11. 

I believe that we've been able to reproduce these issues and are investigating the cause.

**Comment by AnishaLamichhane11** [comment] 2024-02-01 02:59
Could you let me know how long will it take to resolve ?
We are in urgency for the release of the app.

**Comment by nesium** [comment] 2024-02-01 11:50
Issue 1 should be fixed in [2.4.5](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.4.5).

I will update this ticket once we know more about issue 2.

**Comment by nesium** [comment] 2024-02-05 09:43
Hi @AnishaLamichhane11. We've done some digging on issue 2. which did not lead to a conclusion so far unfortunately. 

Does this issue affect only existing conversations, i.e. conversations where one or more messages have been exchanged or does this happen for brand new conversations as well?

If the former is true (existing conversations) could you please share your Website ID and an affected Session ID with us? You can copy the Session ID after selecting the conversation in [app.crisp.chat](https://app.crisp.chat) …

<img width="600" alt="Screenshot 2024-02-05 at 10 33 51" src="https://github.com/crisp-im/crisp-sdk-ios/assets/39174/08ec2f2f-0004-48d8-9f68-596a5ef479f6">

You can share these IDs privately in the chat on [crisp.chat](https://crisp.chat) and reference this issue.

If you have the chance and access to one of the tools, you could also record the traffic by using either [Proxyman](https://proxyman.io) or [Charles](https://www.charlesproxy.com) and share the transcript with us. That would help a lot. Please make sure to enable [SSL Proxying](https://docs.proxyman.io/basic-features/ssl-proxying) for `*.crisp.chat`.

**Comment by AnishaLamichhane11** [comment] 2024-02-06 08:00
Hello @nesium 
After upgrading to the version 2.4.5 the issue 2 (chat view is freezed ) is fixed. 
And about the issue 1,  after the update we haven't faced that issue. Thanks

**Comment by nesium** [comment] 2024-02-06 09:12
Thanks for the update @AnishaLamichhane11. Glad to hear that one of the issues is fixed. I'm going to close this ticket then. In case that you encounter the other issue again please reach out with the information as mentioned above.

**Closed by nesium** 2024-02-06 09:12 UTC
