### ISSUE TITLE
Error Starting Chat using Crisp 1.0.3

### ISSUE THREAD

**Issue by trevinwisaksana** [crisp-im/crisp-sdk-ios#25] opened 2020-08-05 03:32 UTC
Hi,

Upon launching the `ChatViewController`, I sometimes get this error message. I have not set the tokenID and from the error log this may have something to do with the web socket. I wasn't able to capture it though. What's weird is that after about 5 attempts of retrying it would function normally.

![Simulator Screen Shot - iPhone 11 - 2020-08-05 at 10 19 47](https://user-images.githubusercontent.com/20000813/89368695-5b508280-d706-11ea-8a9c-25759e17a33b.png)

**Comment by trevinwisaksana** [comment] 2020-09-10 04:20
Hi,

Just to follow up. This error with starting the chat has become so common that it's unacceptable. I urge your development team to find the source of this quickly and fix it. Moreover, we noticed a spike in our crash rate because of `ChatViewController`. We believe that this UIAlertController seems to be presented so many times it causes a crash because it's trying to present something when there's an alert already being presented. Please look into this ASAP.

Thanks

**Comment by ZComwiz** [comment] 2020-09-19 15:17
Btw it works on iPad but not iPhone...

**Comment by baptistejamin** [comment] 2020-09-30 07:29
We recently found an issue with teams using the bot or our slack feature.

The problem is already fixed, the issue is there is a bug in the new XCode, creating a problem when shipping the pod.

We just wait the fix with the XCode development tools and the fix will be released.

**Comment by 2898117012** [comment] 2020-11-08 15:53
same issue.

**Comment by 2898117012** [comment] 2020-11-15 16:26
I have upgrade to Xcode 12.2. But this issue not fix.

**Comment by archerwindy** [comment] 2020-11-22 08:31
Xcode 12.2 same issue here. Any updates?

**Comment by eliottvincent** [comment] 2020-11-22 10:14
Hello guys. We recently released a new version, have you tried it? https://github.com/crisp-im/crisp-sdk-ios/releases/tag/1.0.6

**Comment by archerwindy** [comment] 2020-11-22 10:15
@eliottvincent Yes, 1.0.6 on Xcode 12.2

**Comment by zzzzjjj** [comment] 2020-12-31 08:45
@eliottvincent  yes, 1.0.6 on Xcode 12.2

**Comment by eliottvincent** [comment] 2020-12-31 09:15
Thanks for confirming. Same behavior on the 1.0.7 we just released?
@nesium will get back to you regarding this.

**Comment by zzzzjjj** [comment] 2020-12-31 09:20
yes， 1.0.6 and 1.0.7 had same behavior, and it works on iPad and some simulator, but not mobile iphone

**Comment by nesium** [comment] 2020-12-31 13:11
Thanks @zzzzjjj. When the chat cannot be started we're printing an error to the Xcode debug console. Could you look out for a message that looks similar to this:

```
[error] The Internet connection appears to be offline.
```
and quote it here? Thank you!

**Comment by Uniphix** [comment] 2021-01-28 21:46
We are getting this same issue and I get this as an output

[error] (Parsing) Found incorrect type for field 'wait_reply' in class Alert. Expected 'one of [show, hide]', found lock instead.

**Comment by nesium** [comment] 2021-02-01 14:38
@Uniphix This has been fixed in the 1.0.9 release. Let us know if you still experience any problems. Thanks!

**Comment by mxmk** [comment] 2021-07-29 13:17
Hi, it seems we have the same issue with some our clients while using the v1.0.13 release. Could you please help? 
Let me know if you need more info. 
Thank you very much.

**Comment by nesium** [comment] 2021-07-29 14:01
Hi @mxmk. If you can reproduce the problem: Are you seeing any output on the console?
If not, could you please try with the latest release first? Thanks!

**Comment by nesium** [comment] 2023-08-07 09:23
Hi everyone,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!

**Closed by nesium** 2023-08-07 09:23 UTC
