### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by toreeliu** [crisp-im/crisp-sdk-ios#41] opened 2021-03-01 07:42 UTC
Is there a way to setup push notification that integrates with APNS or Firebase to notify the user when there is a new message comes?

**Comment by baptistejamin** [comment] 2021-03-01 07:45
Hi, I will check with the team and let you know

**Comment by baptistejamin** [comment] 2021-03-01 07:48
you can do it with web hooks :)
How to use Webhooks? — https://help.crisp.chat/en/article/how-to-use-webhooks-itsagz/

**Comment by toreeliu** [comment] 2021-03-02 02:57
So there won't be a native or pre-build psuh notification just freshchat does? What we need to do is simply add a  "didReceiveRemoteNotification" and "didRegisterForRemoteNotificationsWithDeviceToken" to receive push notification.

**Comment by baptistejamin** [comment] 2021-03-02 10:01
Currently, we recommend using something like OneSignal with webhooks

**Comment by toreeliu** [comment] 2021-03-13 05:55
Is there any plan to build a native push notification for users on Firebase or Amazon SNS?
Also, you have mentioned about OneSignal integration. Is there any update for this?

**Comment by baptistejamin** [comment] 2021-03-15 04:24
Hi there! This is not planned but the team already know about this feedback. Regarding the OneSignal integration, we do not have updates but we will let you know once we have something new rolled out. :)

**Comment by nesium** [comment] 2023-08-07 09:25
Closing this as a duplicate of #17.

**Closed by nesium** 2023-08-07 09:25 UTC
