### ISSUE TITLE
Crash on ios16

### ISSUE THREAD

**Issue by DangerousPixel** [crisp-im/crisp-sdk-ios#84] opened 2023-04-12 12:03 UTC
Hi all ,
I was using older version of library, then I updated my app (last update of library included)
after building via XCode it builds corrupted ipa file, and not working on ios16 .
if I install it on ios 15 it works fine 

extra tip: after decrypting app the installing it on 16 it works with no problems.
I can do that for temporarily, but I want proper way to build it with ios 16 support

thanks

**Comment by nesium** [comment] 2023-04-14 08:58
Hi @DangerousPixel. Thanks for your report.

It's not entirely clear to me what the problem is that you're trying to describe. It sounds to me that you're having trouble installing an IPA that links against iOS 16 on your device. What you haven't mentioned though is why you think that this is a problem with the Crisp library. What steps are you taking to install your app (e.g. Build & Run in Xcode or TestFlight), what is the error message you're seeing and when and where are you seeing it?

**Comment by nesium** [comment] 2023-05-02 08:17
I'll go ahead and close this. Feel free to reopen if this is still an issue and you can provide more information.

**Closed by nesium** 2023-05-02 08:17 UTC
